#!/usr/bin/env bash

fifo_file=/tmp/mytest.fifo

trap 'rm -f "$fifo_file"' EXIT

if [ ! -p "$fifo_file" ]; then
    mkfifo "$fifo_file"
fi

while read -r line<"$fifo_file"; do
    if [[ "$line" == 'quit' ]]; then
        break
    fi
    echo "$line"
done

echo "exiting"
